package com.ayd.avatarproject.util

class Constants {

    companion object{

        //for navigation bundle
        const val MAIN_ARGUMENT = "avatarArg"

        //image url
        const val AANG_IMAGE_URL = "https://static.wikia.nocookie.net/avatar/images/a/ae/Aang_at_Jasmine_Dragon.png/revision/latest/scale-to-width-down/333?cb=20130612174003"
        const val APPA_IMAGE_URL = "https://static.wikia.nocookie.net/avatar/images/6/65/Appa_flying.png/revision/latest/scale-to-width-down/333?cb=20140517110636"
        const val MOMO_IMAGE_URL = "https://static.wikia.nocookie.net/avatar/images/8/80/Momo_staring.png/revision/latest/scale-to-width-down/333?cb=20200802080013"
        const val KATARA_IMAGE_URL = "https://static.wikia.nocookie.net/avatar/images/7/7a/Katara_smiles_at_coronation.png/revision/latest/scale-to-width-down/333?cb=20150104171449"
        const val SOKKA_IMAGE_URL = "https://static.wikia.nocookie.net/avatar/images/c/cc/Sokka.png/revision/latest/scale-to-width-down/333?cb=20140905085428"
        const val TOPH_IMAGE_URL = "https://static.wikia.nocookie.net/avatar/images/4/46/Toph_Beifong.png/revision/latest/scale-to-width-down/333?cb=20131230122047"
        const val ZUKO_IMAGE_URL = "https://static.wikia.nocookie.net/avatar/images/4/4b/Zuko.png/revision/latest/scale-to-width-down/333?cb=20180630112142"
        const val SUKI_IMAGE_URL = "https://static.wikia.nocookie.net/avatar/images/1/14/Suki.png/revision/latest/scale-to-width-down/333?cb=20130819094354"
        const val IROH_IMAGE_URL = "https://static.wikia.nocookie.net/avatar/images/c/c1/Iroh_smiling.png/revision/latest/scale-to-width-down/333?cb=20130626131914"
        const val OZAI_IMAGE_URL = "https://static.wikia.nocookie.net/avatar/images/4/4a/Ozai.png/revision/latest/scale-to-width-down/333?cb=20130612170743"
        const val AZULA_IMAGE_URL = "https://static.wikia.nocookie.net/avatar/images/1/12/Azula.png/revision/latest/scale-to-width-down/333?cb=20140905084941"
        const val ZHAO_IMAGE_URL = "https://static.wikia.nocookie.net/avatar/images/e/e1/Commander_Zhao.png/revision/latest/scale-to-width-down/333?cb=20140103180854"
        const val FENG_IMAGE_URL = "https://static.wikia.nocookie.net/avatar/images/8/8d/Long_Feng_scheming.png/revision/latest/scale-to-width-down/333?cb=20140510202422"

        //descriptions
        const val AANG_DESC = "Aang was a male Air Nomad born in 12 BG and the Avatar during the Hundred Year War, succeeding Avatar Roku[7] and preceding Avatar Korra. As the Avatar of his time, he was the only person capable of using all four bending arts: airbending, waterbending, earthbending, and firebending. He was also one of a select few Avatars and one of the first in many cycles[8] to learn the ancient art of energybending and the first Avatar known to have actively used the technique.\n" +
                "Shortly before the beginning of the Hundred Year War, Aang was frozen in an iceberg for a hundred years; he later emerged, still biologically twelve years old, into a world engulfed by war.[3] During his absence, the Fire Nation had waged war upon the other nations and managed to completely wipe out the pacifistic Air Nomads. It fell to Aang, the Avatar and the last airbender, to end the War by mastering the other three elements and defeating Fire Lord Ozai. He remained a kind and goofy kid at heart throughout his year-long struggle, despite the overwhelming loss of his people and the heavy burdens he was forced to bear. After his victory over the Phoenix King, Aang began a romantic relationship with his close friend, Katara.[9] The couple eventually married and raised a family of three children: Bumi, the oldest, a nonbender who became an airbender later in life; Kya, a waterbender; and the youngest, Tenzin, an airbender."

        const val APPA_DESC = "Appa was Avatar Aang's loyal sky bison, who shared a strong bond with him and Momo as they were all some of the few remaining traces of the Air Nomad civilization.[2] Appa was most noted for his ability to fly in spite of his heavy weight, a feat achieved through airbending, which made him the primary means of transportation utilized by Team Avatar.[3]"

            const val MOMO_DESC = "Momo was a winged lemur and a loyal companion of Avatar Aang and his friends. By late 99 AG, he lived at the Southern Air Temple and was the only known specimen of the winged lemur species to still be alive after the Air Nomad Genocide.[2]"

            const val KATARA_DESC = "Katara is a waterbending master, born in the Southern Water Tribe to Chief Hakoda and his wife Kya. During her childhood, she was the only waterbender living in the Southern Water Tribe. After losing her mother in a Fire Nation raid and her father left to battle against the Fire Nation in the Hundred Year War, she was raised by her paternal grandmother Kanna alongside her older brother Sokka. As a teenager, Katara and her brother discovered the young Air Nomad Avatar, Aang, who had been frozen in an iceberg with his bison, Appa, for a century.[13] In need of a waterbending master, the siblings and Aang left the South Pole on a journey toward the Northern Water Tribe.[14]\n" +
                    "Realizing Aang was the Avatar, Katara and Sokka continued to travel with him across the world as he mastered the remaining elements, earth and fire. She became Aang's waterbending instructor after their departure from the Northern Water Tribe, replacing Master Pakku,[15] who had instructed them during their time there. Her mastery of water made her a formidable asset to the group. The siblings' assistance helped Aang halt the Fire Nation's ambitions of world domination, ending the century-long war, and finally restoring balance to the world.[16]\n" +
                    "\n" +
                    "The murder of her mother[17] and the later departure of her warrior father[13] left Katara feeling traumatized and alone.[18] Though she was cared for by Kanna,[13][14] she invariably found herself filling the mother role left behind by Kya, even to her own older brother. Katara soon took on many of the responsibilities expected of an adult and quickly became independent and strong-willed. Morally and emotionally driven, she developed a great sense of justice and compassion for others, becoming fiercely protective of those in need.\n" +
                    "\n" +
                    "After the Hundred Year War ended, Katara and Aang began a close romantic relationship[16] that eventually led to marriage and raised a family with three children: Bumi, a nonbender who gained the ability to airbend later in life,[19] Kya, a waterbender, and Tenzin, an airbender. Later in life, Katara became highly regarded as a master waterbender, and even said to be the best healer in the world.[20] After Aang's passing, she became Avatar Korra's waterbending teacher[21] and helped her to recover physically from her ordeal with the Red Lotus.[22]"

            const val SOKKA_DESC = "Sokka was a Water Tribe warrior of the Southern Water Tribe and the son of Chief Hakoda and Kya. Following the death of his mother and his father's departure for war, Sokka was raised by his grandmother Kanna along with his younger sister Katara.\n" +
                    "Hakoda left along with all of the other men in his tribe to fight the Fire Nation when Sokka was a young boy. Despite his desire to join his father, Sokka was not permitted to accompany the men on the mission and was left behind.[9] As there were no other teenage boys in the tribe, Sokka was the oldest male in the South Pole and, therefore, left as the leader of the tribe. He assumed responsibility for the tribe, haplessly training children to be future warriors until his sister discovered an Air Nomad named Aang frozen in an iceberg.[9] When he learned that Aang was the Avatar,[10] he was at first skeptical that a child could really save the world. As he and his sister helped Aang on his quest, he began to believe that Aang really was the only hope for peace in the world.\n" +
                    "\n" +
                    "Despite his inability to bend, Sokka became the strategist of the group, constantly trying to prove himself to be a great warrior like his father. He attempted to train the younger children of the Southern Water Tribe in fighting. Sokka was also the \"matter of fact\" guy in the group and did not believe in spirit magic, as he openly mocked it.[11] His leadership skills improved during his travels with the Avatar, culminating with his masterminding the plan for the invasion of the Fire Nation on the Day of Black Sun.[12] His humor and his ability to organize and plan became imperative to the group on their travels. By the conclusion of the Hundred Year War, Sokka became a master swordsman[13] and a great warrior like his father.\n" +
                    "\n" +
                    "After Aang and Zuko formed the United Republic of Nations, Sokka became the representative for the Southern Water Tribe on the United Republic Council, as well as its chairman.[14]"

            const val TOPH_DESC = "Toph Beifong is an earthbending master, one of the most powerful of her time, and the discoverer of metalbending. Blind since birth, Toph was constantly treated condescendingly because of her visual impairment, particularly by her overprotective parents, Lao and Poppy Beifong. Upon discovering badgermoles, earthbending animals who are also blind, she learned how to use earthbending as an extension of her senses. This gave her the ability to \"see\" every vibration that passes through the ground.[14]\n" +
                    "Having developed her own unique style of earthbending, Toph acquired a toughened personality and became famous for winning underground earthbending tournaments under the alias \"The Blind Bandit\", doing so behind her parents' backs.[7] Although initially uninterested in directly aiding the war effort, she eventually chose to leave behind her old life, and travel with Avatar Aang and his friends as his earthbending teacher, when her parents finally became unbearable for her.[15] Toph's total mastery over earthbending, unique personality, and thoughtful pragmatism made her a valuable addition to the team.\n" +
                    "\n" +
                    "After Republic City's formation, Toph became the city's first Chief of Police, forming the Metalbending Police Force to help maintain order.[16] She had two daughters with two different men: Lin, who succeeded her as Chief of Police, and Suyin, who created the metal city of Zaofu. Toph eventually set out to roam the world in search of enlightenment[17] before settling down in the Foggy Swamp.[18]"

            const val ZUKO_DESC = "Zuko is a Fire Nation royal and firebending master who reigned as Fire Lord from 100 AG until his abdication in 167 AG. He is the eldest child and only son of Princess Ursa and Fire Lord Ozai. Originally the primary enemy of Team Avatar, Zuko devoted three years to trying to capture the long-lost Avatar to end his banishment and regain his honor as Crown Prince of the Fire Nation. He is recognizable by the distinctive burn scar on the left side of his face, which was given to him by his father, Ozai, shortly before his banishment as a result of an incident in which he unintentionally disrespected his father by speaking out of turn and refusing to duel him.[13]\n" +
                "With support from his paternal uncle, General Iroh, and after much internal struggle and turmoil, Zuko rejected Ozai and his model of the Fire Nation. He instead joined the Avatar's group to become Aang's lifelong friend and firebending mentor[14] and was determined to end the war and restore both his and the Fire Nation's honor.[15] While Aang defeated Ozai, Zuko, with the help of Katara, defeated his younger sister, Princess Azula, and took his place as Fire Lord, declaring the end of the Hundred Year War and the start of a new era of love and peace.[9]\n" +
                "\n" +
                "At the beginning of his reign, Zuko had to overcome great difficulties and solve several crises, especially those caused by the Harmony Restoration Movement[16] and the New Ozai Society.[17] Nevertheless, he succeeded in maintaining peace and eventually became one of the founders of the United Republic of Nations.[18] Zuko stepped down from his position as Fire Lord in 167 AG and became an ambassador of peace, relinquishing the throne to his daughter, Izumi.[8][19][10]"

            const val SUKI_DESC = "Suki was the leader of one of the Kyoshi Warrior bands of the Earth Kingdom's Kyoshi Island.[2] Having begun her training when she was only eight years old,[3] she was well-respected by her fellow warriors for her leadership and combat skills. When Team Avatar arrived on Kyoshi Island, Suki and a few other Kyoshi Warriors captured them, thinking they were Fire Nation spies, but released them and befriended them after realizing Aang was the Avatar.[1] Inspired by the outsiders for helping save their village from Prince Zuko, she and the other Kyoshi Warriors left the island to help the Earth Kingdom fight against the Fire Nation. During their journey, she protected the Avatar's lost sky bison, Appa, from falling into the enemy's hands, but she and the other Kyoshi Warriors were defeated by Princess Azula, Mai, and Ty Lee.[4]\n" +
                    "Imprisoned in the Fire Nation, Suki was placed within the Boiling Rock, where she hatched a plan to build a sense of community among the prisoners before being betrayed by her ally, Biyu.[2] It was only by good fortune that Sokka and Zuko infiltrated the facility looking for Sokka's captured father, Hakoda, instead finding her.[5] Freed from captivity,[6] Suki later helped Aang and friends defeat the Fire Nation and eventually reunited with her fellow Kyoshi Warriors.[7] Following the end of the Hundred Year War, she continued to lead the Kyoshi Warriors as bodyguards for Fire Lord Zuko, assisting in defeating the New Ozai Society.[8][9] She later rejoined the rest of Team Avatar to put down the bender supremacist insurrection in Cranefish Town.[10][11]"

            const val IROH_DESC = "Iroh was a retired Fire Nation general, a former Crown Prince of the nation, a Grand Lotus of the Order of the White Lotus,[1] a firebending master, and a wise mentor to his nephew Zuko.[5] He was the elder son of Fire Lord Azulon and Ilah and the older brother of Ozai.[6] Iroh's well-known ability to breathe fire and his claims of \"slaying\" the last dragon earned him the honorary title \"The Dragon of the West\".[7][8]\n" +
                "Unlike many other individuals from the Fire Nation, particularly those within his own family, Iroh was a wise, easy-going, and spiritual man. He appreciated and admired the balance of the four elements, and even incorporated aspects of the other elements into his own firebending techniques.[9] Iroh aided Avatar Aang and his companions on several occasions, and was consequently branded as a traitor.[10] An extremely perceptive person, he journeyed to the Spirit World in search of his deceased son Lu Ten.[10][11][12] His knowledge and respect for the four elements allowed him to provide advice to others; he assisted many close associates and friends.[2][7][9][13]\n" +
                "\n" +
                "After the traumatic death of his son, Iroh saw Zuko as his own son rather than his nephew,[14] and encouraged him to choose his own destiny, rather than a fate members of the royal family expected of him. Upon Zuko's coronation as Fire Lord after Ozai's defeat and the conflict's conclusion, he reopened the Jasmine Dragon tea shop, and served tea for the rest of his retirement.[15] When he deemed his business in the mortal world finished, Iroh chose to leave his body behind and travel to the Spirit World, where he continued serving tea to various spirits.[16]"

            const val OZAI_DESC = "Ozai was the ruler of the Fire Nation during the final years of the Hundred Year War, reigning as Fire Lord from 95 to 100 AG.[5] He was the second son of Fire Lord Azulon and Ilah, the younger brother of Iroh, uncle of Lu Ten, husband to Ursa, the father of Prince Zuko and Princess Azula, and the paternal grandfather of Izumi.[6] Ozai was a firebending master and, prior to the end of the war, was believed to be the most powerful firebender in the world.[7]\n" +
                    "After Iroh's only son, Lu Ten, died, Ozai usurped his brother's birthright to the throne[8] in a scheme that resulted in his father's death and Ursa's banishment.[9]\n" +
                    "\n" +
                    "Ozai's rule saw a mass buildup of industry and significant technological advancements.[10] Like his father and grandfather before him, Ozai sought to conquer the other nations and become the supreme ruler of the world. To do this, he planned to utilize Sozin's Comet to burn down the Earth Kingdom, renouncing the title of Fire Lord and declaring himself the Phoenix King, ruler of the world.[11] Before his plans could come to fruition, he was defeated by Avatar Aang, who used energybending to remove his firebending abilities permanently.\n" +
                    "\n" +
                    "After the end of the war and Zuko's crowning, Ozai was sentenced to life in prison for several war crimes.[12] However, he was able to maintain a degree of influence on world politics through some of his loyal followers creating the \"New Ozai Society\" and his son, who occasionally sought advice from Ozai. As a result, the former Fire Lord was indirectly responsible for the failure of the Harmony Restoration Movement.[1]"

            const val AZULA_DESC = "Azula was a princess of the Fire Nation, daughter of Fire Lord Ozai and Ursa, younger sister of Zuko, and older half-sister of Kiyi. She was a key adversary of Team Avatar,[5] chasing Avatar Aang and her banished brother far across the Earth Kingdom accompanied by her then two best friends, Mai and Ty Lee.\n" +
                "A firebending prodigy, Azula was manipulative and obsessed with power. She was a skilled strategist who orchestrated the coup of the Earth Kingdom capital, Ba Sing Se,[6][7] and halted the invasion on the Day of Black Sun.[8]\n" +
                "\n" +
                "Azula harbored deep mental instabilities, believing her mother loved Zuko more than her.[9] Raised by her father in an environment without a mother-figure, Azula had to be nothing less than perfect in her father's eyes in order to gain affection and attention from him. After the betrayal of her two closest friends Mai and Ty Lee, these instabilities were brought up to the surface.[1] Upon the arrival of Sozin's Comet, Azula was soon to be crowned Fire Lord;[10] however, her defeat at the hands of her brother Zuko and Katara caused her to suffer a complete mental breakdown.[11]\n" +
                "\n" +
                "Following her emotional breakdown, Azula was put in a mental health facility to recover,[12] though she eventually joined Team Avatar on their search for Ursa, as part of her secret agenda to betray them and usurp the throne from Zuko. At this quest's completion, however, Azula escaped the team's supervision.\n" +
                "\n" +
                "Sometime after her exile, Azula returned to the Fire Nation Capital in secret. Having finally accepted that she would never be Fire Lord, Azula resorted to manipulating Zuko so that she could rule through him. Gathering a group of female supporters, she took on the guise of the mythical Kemurikage to intimidate Ukano into threatening Zuko. When that failed, Azula and her followers resorted to kidnapping children in the capital, setting the city into civil unrest. Though Zuko and his allies were able to rescue the children, Azula and her followers escaped."

            const val ZHAO_DESC = "Zhao was the leader of the Fire Nation Navy for a brief period in early 100 AG.[5] During his career, he held the ranks of lieutenant, captain, commander,[2] and finally admiral.[3] He was trained by Jeong Jeong to become a master firebender and, as one of the most powerful men in the Fire Nation, took it upon himself to capture Avatar Aang, thus becoming a rival of Prince Zuko.[3] Zhao was a major enemy of Team Avatar in most of the events leading up to his siege of the Northern Water Tribe, during which he killed the Moon Spirit at the Spirit Oasis. This resulted in his downfall by a vengeful Ocean Spirit,[1] who subsequently condemned Zhao to spend eternity in the Fog of Lost Souls in the Spirit World.[4]"

            const val FENG_DESC = "Long Feng was the Grand Secretariat of Ba Sing Se, the leader of the Dai Li, and a very charismatic, influential, and manipulative individual who lusted for power. As Earth King Kuei's closest personal adviser, Long Feng hid the Hundred Year War's existence outside the Earth Kingdom capital's walls while the Dai Li supplanted the king's power over his people.\n" +
                    "For many years, Long Feng acted as de facto dictator of the entire Earth Kingdom, leading the country during the later stages of the Great War. He directed his country's war effort, supported Earth Kingdom armies, and funded rebels in their struggle against the Fire Nation. However, his obsession with keeping the conflict out of Ba Sing Se meant that he did not invest as much attention or aid to the rest of his country as he could have.[2]\n" +
                    "\n" +
                    "With the arrival of Avatar Aang and his team at the city,[1] Long Feng captured their lost flying bison, Appa, as leverage should they disrupt the delicate balance the Dai Li had created.[3] His ulterior motives were exposed by the Avatar when the Dai Li could not hide all evidence of the Fire Nation's invasion from the Earth King, so Long Feng was imprisoned for treason.[4] However, the Dai Li were still loyal to their leader, and Long Feng struck a deal with Princess Azula to give her the Avatar in exchange for power over the city, though Azula double-crossed him and won the loyalty of the Dai Li, claiming Ba Sing Se in the name of the Fire Nation.[5]"




    }

}